### ISSUE TITLE
feature request ip adress

### ISSUE THREAD

**Issue by BillyTi** [RUB-NDS/Terrapin-Scanner#25]
Hey Fabian, awesome work with the scanner. it would be very cool if you choose the -json format so that the ouput also contains the corresponding ip when you run the scanner in a loop against an ip list

regards ;)

**Comment by TrueSkrillor** [comment]
Thanks for the feature request; fully agree with you (otherwise, script-based scanning is more complicated than it should be). I will make sure to add this feature and release a new version as soon as I get to it.

**Comment by BillyTi** [comment]
ya i know what u mean, i tested the scanner in a larger environment. it is then very confusing which are vulnerable and which are not. that would be very helpful, especially for larger companies. but again thank you ;) ...

**Comment by TrueSkrillor** [comment]
FYI: I just released v1.1.3, adding this feature to the scanner. In addition to the IP address, the port will also be included.
