### ISSUE TITLE
Feature: IPv6 compatibility 

### ISSUE THREAD

**Issue by BernhardGruen** [RUB-NDS/Terrapin-Scanner#3]
If I try to scan an IPv6 address I get the following error message:

```
panic: dial tcp: address xxxx:xxxx:xxxx:xxxx::2: too many colons in address
```
The following command lines were tried:

- `terrapin-scanner -connect 'xxxx:xxxx:xxxx:xxxx::2'`
- `terrapin-scanner -connect xxxx:xxxx:xxxx:xxxx::2`

My workaround for the moment:
I use jtesta/ssh-audit for these cases. Joe Testa luckily implemented the scan for terrapin into his software.

**Comment by TrueSkrillor** [comment]
Thanks for the report. This is to be expected given that the socket is always tcp, not tcp6. I try to add support for IPv6 today.

**Comment by TrueSkrillor** [comment]
v1.1.0 is now available, adding support for IPv6. Note that literal IPv6 addresses must be enclosed by square brackets. Happy to hear if that works for you.

**Comment by BernhardGruen** [comment]
Hey @TrueSkrillor,

Thank you for your fast fix and sorry for the late response.
I can confirm that it works as expected using the following command line:
`terrapin-scanner -connect [xxxx:xxxx:xxxx:xxxx::2]:22` (Port is optional)
