### ISSUE TITLE
Windows versions supported?

### ISSUE THREAD

**Issue by Px-x64** [RUB-NDS/Terrapin-Scanner#30]
Hi, the provided binary for Windows/AMD64 crashes on Windows 7 with the following stack
```
M:\>Terrapin_Scanner_Windows_amd64.exe
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall()
        /usr/lib/go/src/runtime/sys_windows_amd64.s:65 +0x75 fp=0x22fca0 sp=0x22 fc80 pc=0x466215
rax     0x0
rbx     0x632ee0
rcx     0x685ac0
rdi     0x7fffffde000
rsi     0x22fea0
rbp     0x22fde0
rsp     0x22fc78
r8      0x0
r9      0x22fee0
r10     0x657818
r11     0x21
r12     0x22fec0
r13     0x1
r14     0x632880
r15     0x0
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b
```
Which Windows versions are supported? Or it requires some additional components to be installed?

**Comment by TrueSkrillor** [comment]
Hi there,

Our pre-built binaries are cross-compiled to support Windows (amd64). However, Go has removed support for Windows 7 in 1.21, the version we use to build those binaries. To get the scanner up and running on Windows 7, you will need to build the scanner yourself using a Go version between 1.18 and 1.20 (see README for instructions). Alternatively, you may build a custom Docker image by adjusting the Golang version in the Dockerfile.
