### ISSUE TITLE
Incompatibile GLIBC version on RHEL-7

### ISSUE THREAD

**Issue by ElvishArtisan** [RUB-NDS/Terrapin-Scanner#8]
'Terrapin_Scanner_Linux_amd64' throws:

```/lib64/libc.so.6: version `GLIBC_2.34` not found (required by ./Terrapin_Scanner_Linux_amd64)``` 

on RHEL-7 (x86_64). Any chance of getting a statically-linked binary?

**Comment by TrueSkrillor** [comment]
Thanks for the report. I intended the binaries to be statically linked (though I didn't check that). The [v1.1.0 binaries](https://github.com/RUB-NDS/Terrapin-Scanner/releases/tag/v1.1.0) and onwards are now built with `CGO_ENABLED=0`, yielding statically linked binaries.

Fixed in #9.

**Comment by ElvishArtisan** [comment]
Thanks! Tested and verified working on RHEL-7.
